services:
  dataflow-sentinel:
    build: .
    container_name: dataflow-sentinel

    network_mode: "host"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./data:/app/data
